run:
  timeout: 5m
  go: "1.23"

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - misspell
    - unconvert
    - bodyclose

linters-settings:
  gofmt:
    simplify: true

issues:
  exclude-rules:
    # Allow blank identifier for intentional no-ops (e.g. server shutdown errors).
    - linters: [errcheck]
      text: "metricsSrv.Shutdown"
